kind: wasmer.io/App.v0
name: Lyfla
app_id: da_R9EIBt1U5YxN
owner: pujosety
package: .
env:
  STORAGE_PUBLIC_PATH: /data/lyfla-public
volumes:
  - name: lyfla-public
    mount: /data/lyfla-public
jobs: []
scripts:
  build: |
    composer run-script post-update-cmd
    npm run build
  install: |
    composer install --optimize-autoloader --ignore-platform-reqs --no-scripts --no-interaction
    npm install
  start: |
    php artisan config:clear \
      && php artisan cache:clear \
      && php artisan migrate --force --no-interaction \
      && php artisan db:seed --class=PermissionSeeder --force --no-interaction \
      && php artisan config:cache \
      && php artisan route:cache \
      && php -S 0.0.0.0:${PORT:-8080} -t public
annotations:
  anybuild.run/config:
    commands:
      after_deploy: php artisan migrate --force --no-interaction
    composer_build_script: post-update-cmd
    composer_enable: true
    name: out
    node_build_command: npm run build
    node_install_inputs:
    - package.json
    node_package_manager: npm
    npm_version: '11'
    php_framework: laravel
    php_public_dir: public
    phpix: true
  anybuild.run/provider: laravel
  anybuild.run/version: 0.33.0
  wasmer.io/version: 7.5.0
enableDatabase: true
enable_email: true
