<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Media library for the CMS.
 *
 * WHY A SEPARATE MIGRATION
 *
 * The `cms_posts` migration is shipped and must not be edited — someone has
 * already migrated a database with it, and re-running an edited old migration
 * does not change that database. So the media tables are additive here.
 *
 * WHAT THIS IS NOT
 *
 * It is not a second document store. Student documents are private and served
 * through an authorised route; CMS images are published to the school site.
 * Sharing one table would mean one row carrying a flag that decides whether
 * the file is world-readable, and every reader would have to remember to
 * check it. Two tables, two serving paths, no shared blast radius.
 *
 * WHY `path` IS THE ONLY HANDLE
 *
 * The stored path is generated, not chosen — see CmsMediaService. It is
 * relative to the disk, and there is no `url` column: a URL is derived from
 * (disk, path) at render time, so moving the disk or switching to a bucket
 * rewrites every link without a data migration.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('cms_media', function (Blueprint $table) {
            $table->id();

            // Which disk, because the path is meaningless without it. Recorded
            // per row so one item can be migrated to another disk later
            // without rewriting every other row that shares its prefix.
            $table->string('disk', 32);

            /*
             * Relative to the disk root, generated by the service. NEVER the
             * browser's filename: this is the field an attacker would put
             * `../../.env` into.
             */
            $table->string('path', 255);

            // Kept for the library listing. Not used to decide anything.
            $table->string('original_name', 255)->nullable();

            // Sniffed from the bytes with finfo at upload time.
            $table->string('mime', 80);

            // Bytes, not KB. A size shown to a human is a rendering concern.
            $table->unsignedBigInteger('size');

            // From getimagesize(). Nullable: a GIF that decodes but reports no
            // dimensions is still a usable image, and rejecting it would be a
            // lie about what the library can hold.
            $table->unsignedInteger('width')->nullable();
            $table->unsignedInteger('height')->nullable();

            // Alt text is an accessibility field, so the editor is asked for
            // it rather than a human guessing later. Caption is the visible
            // line under the image.
            $table->string('alt_text', 255)->nullable();
            $table->text('caption')->nullable();

            $table->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();

            $table->timestamps();

            /*
             * Deleting an image is a SOFT delete on purpose. An article that
             * is live may still reference the path in its body, and a hard
             * delete turns a "this photo is no longer used" cleanup into a
             * broken page on the public site that nobody has a way to fix.
             */
            $table->softDeletes();

            // The library listing: newest first, never more than a screen.
            $table->index(['deleted_at', 'created_at'], 'cms_media_library_index');
        });

        /*
         * One image can be used by several articles — the school logo, the
         * headmaster's photo — and one article can have several images.
         *
         * `sort_order` rather than a timestamp: the order images appear in an
         * article is editorial, and letting the database invent it from
         * insertion order makes reordering an article a delete-and-reinsert.
         */
        Schema::create('cms_post_media', function (Blueprint $table) {
            $table->id();
            $table->foreignId('cms_post_id')->constrained()->cascadeOnDelete();
            $table->foreignId('cms_media_id')->constrained()->cascadeOnDelete();
            $table->unsignedSmallInteger('sort_order')->default(0);
            $table->timestamps();

            // A double-submitted form must not attach the same image twice.
            $table->unique(['cms_post_id', 'cms_media_id'], 'cms_post_media_unique');
            $table->index(['cms_post_id', 'sort_order'], 'cms_post_media_order_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('cms_post_media');
        Schema::dropIfExists('cms_media');
    }
};
